///////////////////////////////////////////////////////
//
// Language definition for Admin Tool
//
///////////////////////////////////////////////////////
const VER_INFO := "Admin Tool by Kri v1.1 beta";
///////////////////////////////////////////////////////
const SKILL_CAP := 700;
const STATS_CAP := 225;
///////////////////////////////////////////////////////
const PICK_ACCOUNT := "Pick an account";
const PICK_ACC_BY_NAME := "Search an account";
const END_BUTTON_TEXT := "Quit";
const ADMIN_ON := "Administrating: ";
const BAN_MTF := "BAN !";
const JUST_BANNED := "You've just banned ";
const IS_BANNED := "Banned!";
const JUST_UNBANNED := "Unbanned ";
const UNBAN_IT := "Unban ";
const ACC_CHARACTERS := "Accounts: ";
const NO_CHARACTER  := "-= NONE =-";
const CHAR_STAT := "Stats";
const CHAR_SKILLS := "Skills";
const DEL_CHAR := "Delete";
const DELETED_CHAR := "You've deleted a character";
const DEL_CHAR_Q := "Delete?";
const SUMMON_CHAR := "Summon";
const GOTO_CHAR := "GoTo";
const SEND_CHAR := "Send";
const CHAR_STR := "STR: ";
const CHAR_DEX := "DEX: ";
const CHAR_INT := "INT: ";
const REQUEST_NEW_VALUE := "Give new value";
const CHANGED := "Changed.";
const IS_ONLINE := "-= ONLINE =-";
const IS_OFFLINE := "-= OFFLINE =-";
const EDIT_SKILLS := "Edit Skills";
const CANCELED := "Canceled.";
const EDIT_CPROPS := "Edit CProps";
const LAST_IP := "Last IP: ";
const LAST_LOGGED_IN := "Last logged in ";
const DAYS_AGO := " days ";
const HOURS_AGO := " hours ";
const MIN_AGO := " minutes ";
const SEC_AGO := " sec. ago";
const SEC_AGO2 := " sec.";
const CREATED_AGO := "Created: ";
const IS_ALRDY_PLAYING := "Is playing: ";
const ACC_NOTES := "Notes: ";
const EDIT_NOTES := "Edit notes";
const NOTES_ON_ACC := "Notes on account ";
const SAVE_IT := "Save ";
const CMDLEV := "CMDLevel: ";
const KICK_IT := "Kick";
const CHR_GENDER := "Sex: ";
const IS_HIM := "male";
const IS_HER := "female";
const IS_NEITHER := "neither";
const CHANGE_SEX := "Chenge to what?";
const ASK_IF_SURE := "Are you sure?!";
const DESTROY_ACC := "Destroy account";
const WEIGHT_INF := "Weight: ";
const RES_IT := "Ressurect";
const KILL_IT := "Kill";
const OPEN_BANK := "Open Bank";
const OPEN_BACKPACK := "Open plecak";
const WIPE_BANK := "Wipe Bank";
const WIPE_BACKPACK := "Wipe plecak";
const SHOW_PPR_DOLL := "Show paperdoll";
const HP := "HP ";
const ST := "ST ";
const MP := "MP ";
const WHAT_DELAY := "What delay?";
const WHAT_IS_HE_TRAINING := "What is he training?";
const SEARCH_FOR_PASSIVE_TRN := "Search for cheaters";
const DELAY_NOT_BIGGER_THAN := "Delay not bigger than ";
const DELAY_NOT_SMALLER_THAN := "Delay not smaller than ";
const ACTIVATING := "Activating...";
const CHECKING := "Checking...";
const IS_TRAINING := " is training: ";
const FREEZE := "Freeze";
const UNFREEZE := "Unfreeze";
const SQUELCH := "Squelch";
const UNSQUELCH := "Unsquelch";
const JAIL := "Jail";
const UNJAIL := "Unjail";
const ON_HOW_LONG := "On how long?";
const SEARCH_ONLINE_PLAYERS := "Pick from online chars";
const CHANGE_TO_WHAT := "Change to what ";
const SEARCH_FOR_WRONG_CHAR := "Search for wrong chars";
const GIVE_UNAME := "Give a name ";
const GIVE_PASS := "Give a passwd ";
const CREATED_ACC := "Create an account";
const UNAME_TAKEN := "That acc. already exists!";
const CREATE_NEW_ACC := "Create new acc.";
const CHANGE_PASSWD := "Change passwd";
const NO_SPACES_IN_PASS := "No spaces in passwd!";
const PASS_TOO_LONG := "Password is too long!";




